### ISSUE TITLE
cargo fmt?

### ISSUE THREAD

**Issue by h3mosphere** [dima634/baby_shark#11]
I am wondering if you are amenable to using cargo fmt?

I'm using vscodium & had formatting on by default (which seems to be the norm with most projects), and it caused my first commits to have alot of formatting noise. I have turned it off for this project, but it might be an issue with new committers in the future.

Thanks

**Comment by h3mosphere** [comment]
Also, there are a couple of formatting errors that come up in vscodium due to unnecessary braces etc.

**Comment by dima634** [comment]
I have started to use cargo fmt for this repo but prefer to keep it in manual mode. Sometimes autoformatting gives unpleasant results.
