### ISSUE TITLE
Simplification doesn'nt appear update face indices on mesh

### ISSUE THREAD

**Issue by h3mosphere** [dima634/baby_shark#12]
IncrementalDecimator::decimate doesn't remove/remap face indices when decimating.

For instance, in an updated examples/simplification.rs, this will output mesh vertices (apparently) referencing old position indices.

```rust
use std::path::Path;

use baby_shark::{
    decimation::{edge_decimation::ConstantErrorDecimationCriteria, prelude::EdgeDecimator},
    io::stl::{StlReader, StlWriter},
    mesh::{corner_table::prelude::CornerTableF, traits::Mesh},
};

fn main() {
    let mut reader = StlReader::new();
    let mut mesh: CornerTableF = reader
        .read_stl_from_file(Path::new("./test_files/violin.stl"))
        .expect("Read mesh from STL");

    let decimation_criteria = ConstantErrorDecimationCriteria::new(0.01f32);

    let mut decimator = EdgeDecimator::new().decimation_criteria(decimation_criteria);
    decimator.decimate(&mut mesh);
    for face_idx in mesh.faces() {
        let face = mesh.face_vertices(&face_idx);
        if face.0 > mesh.vertices().count()
            || face.1 > mesh.vertices().count()
            || face.2 > mesh.vertices().count()
        {
            println!(
                "faces index out of bounds: pl {} {} {} {}",
                mesh.vertices().count(),
                face.0,
                face.1,
                face.2
            );
        }
    }
    let writer = StlWriter::new();
    writer
        .write_stl_to_file(&mesh, Path::new("decimated.stl"))
        .expect("Save mesh to STL");
}

```

**Comment by h3mosphere** [comment]
This could probably do something similar to what the stl_reader does via merge_points, although this is probably not the most performant.

**Comment by dima634** [comment]
It is done intentionally for a couple of reasons:
- This allows `VertexDescriptor` to remain valid even if the vertex was removed from the mesh
- Resizing/reshuffling internal `Vec` where vertices are stored would decrease performance significantly for operations like edge collapse

Generally `VertexDescriptor` should not be treated like a vertex index. External code is not supposed to know about implementation details and should treat `VertexDescriptor` as something more abstract. Probably it makes sense to wrap `usize` (`VertexDescriptor` type of `CornerTable`) using new type idiom so it is less transparent how it is implemented.

**Comment by dima634** [comment]
Also, I was thinking of adding another method to `EditableMesh` trait that will collect garbage after decimation/remeshing operation is finished.

**Comment by h3mosphere** [comment]
> It is done intentionally for a couple of reasons:
> 
> * This allows `VertexDescriptor` to remain valid even if the vertex was removed from the mesh
> * Resizing/reshuffling internal `Vec` where vertices are stored would decrease performance significantly for operations like edge collapse

OK, performance alone is reason enough. 

> 
> Generally `VertexDescriptor` should not be treated like a vertex index. External code is not supposed to know about implementation details and should treat `VertexDescriptor` as something more abstract. Probably it makes sense to wrap `usize` (`VertexDescriptor` type of `CornerTable`) using new type idiom so it is less transparent how it is implemented.

Having as a type alias works fine enough. If moving to newtype necessitates a bunch of .0 code, I'd prefer to keep it as is IMHO.

**Comment by h3mosphere** [comment]
> Also, I was thinking of adding another method to `EditableMesh` trait that will collect garbage after decimation/remeshing operation is finished.

This would be nice. For the moment though, I can just round-trip to a Vec / Cursor using the write_stl & read_stl methods.

**Comment by h3mosphere** [comment]
I had a quick look, and came up with this https://github.com/h3mosphere/baby_shark/commit/26ebbfd859b6de92a5b83712de56955d34df1388.

I'll create a pull request, any comments welcome.

**Comment by h3mosphere** [comment]
Closing this.
