### ISSUE TITLE
Add feature to restrict offset algorithm only in positive half-space of mesh triangles

### ISSUE THREAD

**Issue by Nevsden** [dima634/baby_shark#34]
Is it an easy feature to make offset allow to offset only in a certain direction such as e.g. the positive half-space of each triangle of the mesh? This would allow a mesh to offset in normal direction of the mesh but not in the negative direction.

For clarification: (I require) this feature only for meshes with holes (e.g. meshes which arrive from meshing a 3d scan). I want to offset a meshed 3d scan in its normal direction for a more natural mesh evolution when slicing the mesh with a build-up volume in 3d printing. Therefore the starting 3d scan represented as a mesh needs to be offseted by a build-up height as many times as fits into the build-up. After each offset, the offseted mesh is sliced against the build-up mesh. As long as the offset mesh intersects with the build-up this operation is looped.

**Comment by dima634** [comment]
The volume offset supports both inward and outward directions. But it requires mesh to be closed (small holes are allowed though). Have you found a way to do what you described using this library?

**Comment by Nevsden** [comment]
I have the special case of an open mesh, meaning the input mesh for the algorithm already has holes. Think of the mesh as a 3d scan of a freeform plane. In case of "outward" offsetting, the algorithm always expands in both directions of the mesh. Maybe this is only possible this way by design.
