### ISSUE TITLE
panic when using `IncrementalRemesher`

### ISSUE THREAD

**Issue by thelazyone** [dima634/baby_shark#8]
I was trying out the features of this (great) library, and somehow I couldn't use the remesher, no matter how simple the input stl is. 

My stripped down rust code is as follows:

```
use std::path::Path;

use baby_shark::{
    io::stl::{StlReader, StlWriter}, 
    remeshing::incremental::IncrementalRemesher,
    mesh::corner_table::prelude::CornerTableF
};

fn main() {
    let mut reader = StlReader::new();
    let mut mesh: CornerTableF = reader.read_stl_from_file(Path::new(
        "H:/Other computers/My Computer/- Graphics & Projects/Models/3D/Wastelands/basic_cube.stl")).expect("Read mesh from STL");
    

    let remesher = IncrementalRemesher::new()
        .with_iterations_count(10)
        .with_split_edges(true)
        .with_collapse_edges(true)
        .with_flip_edges(true)
        .with_shift_vertices(true)
        .with_project_vertices(true);
    remesher.remesh(&mut mesh, 0.002f32);

    let writer = StlWriter::new();
    writer.write_stl_to_file(&mesh, Path::new("out.stl")).expect("Save mesh to STL");
}
```

Even running with RUST_BACKTRACE=1 I can't seem to find a clear culript for the panicking. 
A similar program calling the `EdgeDecimator ` instead of the `IncrementalRemesher` works fine.

I'm attaching the basic_cube.stl below.
[basic_cube.zip](https://github.com/dima634/baby_shark/files/12066527/basic_cube.zip)

**Comment by dima634** [comment]
I believe this issue is fixed in the last commit (0.1.6 version of the crate). Please let me know if it is still happening to you.
